lwtnn/lwtnn

- converters/keras2json.py
Keras does not support the 'activation' key for maxout layers. Instead, an additional layer can be added if so desired e.g. via `model.add(Activation('relu'))`. It should be save though to just take a `'linear'` activation function for maxout layers instead to preserve the current convention.
I checked the assert statement and in case an activation key is wrongly placed in the maxout layer of the architecture file, Python will throw an AssertionError.
(cherry picked from commit 9d7bc5376b91d719433489c2f885f05d9668f439)
> 'activation' handling in maxout layers

- src/LightweightNeuralNetwork.cxx
- src/lwtnn-test-highway.cxx
I actually noticed that I had my (W, b) and (W_carry, b_carry) switched. I fixed that. 
I also created a gist (http://nbviewer.jupyter.org/gist/mickypaganini/e997d21682a24e6e8c474af25760afa0) where I use the same values as in lwtnn-test-highway.cxx to evaluate the same pattern with Keras. The results now match. You can check this by simply running `./bin/lwtnn-test-highway` and compare the outputs to those in the gist.
> Fixed bug with flipped matrix order when instantiating Highway, add comparison to Keras

- converters/keras2json.py
This assumes that the value of epsilon does not change from 1 BN layer to the next (i.e. someone manually changing the value in each BN layer they create). Since this value is really just a fudge factor that people shouldn't be setting anyway, I doubt this will happen.
> get epsilon value from json file for normalization layer.

- include/lwtnn/LightweightNeuralNetwork.hh
- include/lwtnn/Stack.hh
- src/LightweightNeuralNetwork.cxx
- src/Stack.cxx
Code built as part of the ATLAS release should be consistent with ATLAS naming conventions.
(The existing code is anyway in violation of the C++ standard which reserves to the implementation
all names starting with a underscore followed by an uppercase letter.)
This should be propagated to devval.
> Comply with ATLAS member naming conventions.

- makefile
The makefile now checks for three environment variables:
- LWTNN_CXX_FLAGS: extra compiler options
- LWTNN_LDFLAGS: extra linker flags
- LWTNN_LIBS: extra libraries
Hopefully this makes it easier to avoid hacking the makefile in custom
environments.
> Allow the user to set compile options

- CMakeLists.txt
This is to get a handle on how to compile from scratch when I put in Athena and have to use cmake.
It's probably not a bad idea to have generally, but I'll leave it up to you whether or not you want this.
Something quite interesting, there are a loooot of warnings on lxplus (stupid indentation warnings etc. because of Eigen.), but none when building on Mac. Maybe we don't wan't -Wall flag set? not sure why it only displays them with cmake build and not normal make build.
Anyways, some instructions:
**Setting up the correct env in lxplus**
```
lsetup root 
localSetupSFT releases/LCG_88/eigen/3.2.9
localSetupBoost  boost-1.60.0-python2.7-x86_64-slc6-gcc49
export EIGEN_INC=/cvmfs/sft.cern.ch/lcg/releases/LCG_88/eigen/3.2.9/x86_64-slc6-gcc49-opt/include/eigen3
export BOOST_INC=export …
```
> CMake build

- CMakeLists.txt
Change the way in which boost and eigen are found. Now by default they are looked for in /usr/local/include. If not found, it fails and set the paths manually.
I.e. to use this on lxplus, you don't even need to setup anything fancy, but rather just point it to the headers.
```
lsetup "gcc 620_x86_64_slc6"
lsetup "cmake 3.6.0"
cmake -DEIGEN_INC=/cvmfs/sft.cern.ch/lcg/releases/LCG_88/eigen/3.2.9/x86_64-slc6-gcc49-opt/include/eigen3 -DBOOST_INC=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/boost/boost-1.60.0-python2.7-x86_64-slc6-gcc49/boost-1.60.0-python2.7-x86_64-slc6-gcc49/include ../lwtnn
```
This is needed so that I can make use of this CMakeLists.txt file for the Athena build, see here: https://gitlab.cern.ch/jwsmith/atlasexternals/tree/out_source_lwtnn
I also removed some …
> Cmake tweaks

- CMakeLists.txt
(Avoid property tree errors. I'm not actually sure which version
this was added, but this is safe. )
> Required version of boost no less than 1.54

- CMakeLists.txt
- include/lwtnn/lightweight_nn_streamers.hh
- src/lightweight_nn_streamers.cxx
- tests/test-nn-streamers.cxx
- tests/travis-build-cmake.sh
Hi,
While trying to build the latest ATLAS analysis software release against lwtnn on macOS, I encountered the following build failure:
```
[ 89%] Building CXX object Reconstruction/Jet/BoostedJetTaggers/CMakeFiles/BoostedJetTaggersLib.dir/Root/HbbTaggerDNN.cxx.o
In file included from /Users/krasznaa/ATLAS/sw/ab/athena/Reconstruction/Jet/BoostedJetTaggers/Root/HbbTaggerDNN.cxx:5:
In file included from /Users/krasznaa/ATLAS/sw/ab/athena/Reconstruction/Jet/BoostedJetTaggers/BoostedJetTaggers/HbbTaggerDNN.h:10:
In file included from /Users/krasznaa/ATLAS/sw/ab/athena/Control/AthToolSupport/AsgTools/AsgTools/AsgTool.h:13:
In file included from /Users/krasznaa/ATLAS/sw/ab/athena/Control/AthToolSupport/AsgTools/AsgTools/AsgMessaging.h:11: …
```
> clang-9.0 fix, master branch (2017.12.08.)

- tests/check-conversion.sh
As Dan pointed out the old test never actually returned 1 if there was a failure.
Whoops.
This fixes that.
> Return 1 if tests fails

- src/LightweightGraph.cxx
In a graph with multiple outputs it's possible that only some inputs
will be needed to compute a given output. Prior to this commit,
LightweightGraph would eagerly convert all inputs into to the Eigen
representation before passing them to the Graph. This meant all of the
inputs had to exist in the LightweightGraph input map, even those
which the graph doesn't use.
This commit pushes the std::map to Eigen conversion into the Source
object, which means that the conversion only takes place if it's
required to compute the output in question.
> Look up LightweightGraph inputs lazily

- CMakeLists.txt
- README.md
- include/lwtnn/Graph.hh
- include/lwtnn/LightweightGraph.hh
- include/lwtnn/Source.hh
- include/lwtnn/Stack.hh
- src/LightweightGraph.cxx
- src/Stack.cxx
- Marked overriding methods as 'override'
- Added more compiler warning options
- Added default virtual destructor for ISource base class (otherwise a warning is generated)
- Fixed missing initializer warning for ActivationConfig in Stack.cxx by setting alpha to zero for initialization
- ~Set CXX standard to 17, but 11 is still minimum required~
- Muted compiler warnings coming from Eigen and Boost as they cannot be fixed by code in this project (See CMakeLists.txt)
- Fixed typo in README.md
> Fixed compiler warnings and README typo

- .travis.yml
- tests/travis-build-cmake.sh
This is following up on @VukanJ's merge request to silence warnings and clean things up for C++17. We agreed to stick to C++11 by default since the README says it's supported, but standard is getting pretty old.
> Add C++17 standard to the travis build matrix

- README.md
- converters/keras_layer_converters_common.py
- converters/kerasfunc2json.py
- include/lwtnn/Graph.hh
- include/lwtnn/NNLayerConfig.hh
- scripts/CustomLayers.py
- scripts/lwtnn-test-keras-functional.py
- src/Graph.cxx
- src/parse_json.cxx
Added a sum layer to support deep set architectures. This layer doesn't
currently exist in Keras, so a Keras implementation was added to
scripts/CustomLayers.
Also add support for sequence inputs in lwtnn-test-keras-functional.
> Add sum layer for deep sets

- converters/keras2json.py
At some point it seems that Keras started storing sequence models with the layers nested more deeply, with the structure
```
{
"class_name": "Sequential", "config": {
"name": "sequential_1",
"layers": [...]
}
}
```
this broke the `keras2json.py` converter because it expected `config`
to be a list of layers.
> Fix bug in sequence conversion for from Keras 2.2

- .zenodo.json
- README.md
- converters/keras_v2_layer_converters.py
- scripts/CustomLayers.py
New swish implementation : [Keras-contrib](https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/advanced_activations/swish.py).
Models trained in the old swish implementation can be easily translated to the new one within keras. So LWTNN doesn't need to continue supporting the old version. The C++ side is unchanged, changes only at the converter side.
Choosing _not_ to make `Keras-contrib` a dependency, so the swish implementation is copied into `CustomLayers.py`. It will _not_ be automatically updated with an update in `Keras-contrib`.
Solves https://github.com/lwtnn/lwtnn/issues/87.
> Update Swish to support Keras-contrib implementation

- .travis.yml
The CI builds started failing because the python version was so old. Bumped
python to 3.8, ubuntu to bionic.
> Bump ubnutu and python versions in CI

- converters/kerasfunc2json.py
Apparently newer version of keras have renamed the 'Model' class to
'Functional'. Nothing else seems different, so for now we'll just relax the
requirement on the class_name.
> Allow 'Functional' class models to be converted

- scripts/lwtnn-split-keras-network.py
Keras isn't as stable as h5py and json. This commit removes the keras dependency from the network splitting function.
> Remove Keras from network splitter

- CMakeLists.txt
- include/InputPreprocessor.hh
- include/lwtnn/Graph.hh
- include/lwtnn/LightweightGraph.hh
- include/lwtnn/LightweightNeuralNetwork.hh
- include/lwtnn/Source.hh
- include/lwtnn/Stack.hh
- include/lwtnn/generic/Graph.hh
- include/lwtnn/generic/Graph.tcc
- include/lwtnn/generic/InputPreprocessor.hh
- include/lwtnn/generic/InputPreprocessor.tcc
- include/lwtnn/generic/LightweightGraph.hh
- include/lwtnn/generic/LightweightGraph.tcc
- include/lwtnn/generic/LightweightNeuralNetwork.hh
- include/lwtnn/generic/LightweightNeuralNetwork.tcc
- include/lwtnn/generic/Source.hh
- include/lwtnn/generic/Stack.hh
- include/lwtnn/generic/Stack.tcc
- include/lwtnn/generic/eigen_typedefs.hh
- src/LightweightGraph.cxx
- src/LightweightNeuralNetwork.cxx
- src/lwtnn-test-graph.cxx
This is cleanup after #103. The main changes are:
- Remove a bunch of trailing whitespace.
- Add back some headers that were moved into `generic/`, to prevent us from breaking any old code.
> Generic cleanup

- .gitignore
- .travis.yml
- CMakeLists.txt
- tests/install/CMakeLists.txt
- tests/install/test-lwtnn.cxx
- tests/travis-build-cmake.sh
There were quite a few things missing if someone used CMake to install this library. 
This should fix a few of them. I also asked the cmake build script in the CI to install the library and then try to build another library and link against it, so hopefully we can catch more of these issues in the future.
The original CMakeLists file was written by @krasznaa, and he has far more experience with CMake than I do, so I'll wait to see if he has any suggestions.
> Add a test for the cmake installation, fix cmake bugs

- converters/keras_v2_layer_converters.py
The keras converters for time distributed layers missed some edge cases: specifically they weren't supporting time distributed batch normalization layers. This should make the support more generic.
> Fix keras conversion for time distributed layers

- include/lwtnn/NNLayerConfig.hh
- include/lwtnn/generic/Stack.hh
- include/lwtnn/generic/Stack.tcc
- src/parse_json.cxx
A few of the activation functions were calling `std::function` on every element, via `UnaryActivationLayer`. This meant dereferencing a pointer for every element, which might cost something. This merge request replaces some of those activation functions with something more efficient.
I'm leaving the older implementations around for the sake of benchmarks. These can be accessed by suffixing the activation name with `_legacy` in the lwtnn configuration files. They will probably be removed in the future, assuming no benchmark indicates a need to keep them.
> Reduce calls to std::function in activation functions

- CMakeLists.txt
For whatever reason the URL that we were getting boost from (in the builds that
install a builtin boost) stopped working. I updated it based on the URL I found
on 'www.boost.org', hopefully that is more robust.
Maybe @krasznaa has a reason to use the boost URL that I'm replacing here?
> Update URL for builtin boost

- .github/workflows/ci.yml
Resolves #136 
This PR adds **testing** against `gcc` `v11` through the use of the [`lwtnn/build-base:gcc-v11.1.0` image](https://github.com/lwtnn/build-base) and is able to reproduce the build failure described in Issue #136. Fixing the build error is out of scope for this PR and should fixed in a follow up PR once this PR has been merged.
```
* Add CI stage to test the build against gcc v11 using the ltwnn/build-base images
- c.f. https://github.com/lwtnn/build-base
* Run the test suite using the C++17 standard
```
> test: Add test build against ltwnn/build-base gcc v11 image

- include/lwtnn/NNLayerConfig.hh
- include/lwtnn/Stack.hh
- include/lwtnn/generic/FastGraph.hh
- include/lwtnn/generic/FastGraph.tcc
- include/lwtnn/generic/FastInputPreprocessor.hh
- include/lwtnn/generic/FastInputPreprocessor.tcc
- include/lwtnn/generic/Graph.hh
- include/lwtnn/generic/Graph.tcc
- include/lwtnn/generic/InputPreprocessor.tcc
- include/lwtnn/generic/LightweightGraph.hh
- include/lwtnn/generic/LightweightGraph.tcc
- include/lwtnn/generic/LightweightNeuralNetwork.hh
- include/lwtnn/generic/LightweightNeuralNetwork.tcc
- include/lwtnn/generic/Source.hh
- include/lwtnn/generic/Stack.hh
- include/lwtnn/generic/Stack.tcc
- include/lwtnn/lightweight_network_config.hh
- src/FastGraph.cxx
- src/FastInputPreprocessor.cxx
- src/Stack.cxx
- src/lightweight_nn_streamers.cxx
- src/lwtnn-benchmark-rnn.cxx
- src/lwtnn-test-arbitrary-net.cxx
- src/lwtnn-test-fastgraph.cxx
- src/lwtnn-test-graph.cxx
- src/lwtnn-test-lightweight-graph.cxx
- src/lwtnn-test-rnn.cxx
- src/test_utilities.cxx
- src/test_utilities.hh
Resolves #138 
This is enough to resolve namespace issues with `gcc` `v11`.
Replacing `size_t` with `std::size_t` everywhere avoids (as @dguest has pointed out)
>  included C libraries leaking up into the C++ code
and hopefully any further issues with this. All instances in the codebase are changed as can be seen by
```console
$ git grep "size_t" | grep -v "std::"
```
returning nothing.
It is technically enough to just change all instances that appear in a `std::vector` to resolve Issue #138, but this PR gets all instances to avoid future problems.
```
* Use 'std::' namespace for size_t everywhere in the codebase
- Avoid problems with collisions of C libraries
```
This should ideally be merged _after_ PR #137 is merged.
> fix: Use 'std::' namespace for size_t

- .github/workflows/ci.yml
Resolves #140 
Add C++20 to both GHA server jobs (`test`) and to containerized `lwtnn/build-base` environment tests.
```
* Add C++20 as a tested C++ standard in CI
- Add 'STANDARD=20' to build matrix 'build-system' options in tests job
- Add 'cxx-standard' as built matrix option in build-base job and add 20 as option
```
> ci: Add C++20 C++ standard to testing matrix

- .github/workflows/ci.yml
- CMakeLists.txt
- tests/install/CMakeLists.txt
If only one CMake version is given to `cmake_minimum_required` then CMake will force that version to be used, even if a more updated CMake version is available. So instead of providing only a single CMake version, provide a range of supported CMake versions.
c.f. [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/basics.html) by Henry Schreiner (@henryiii)
```
* If only one CMake version is given to cmake_minimum_required then
CMake will force that version to be used, even if a more updated CMake
version is available. So instead of providing only a single CMake
version, provide a range of supported CMake versions.
- c.f. An Introduction to Modern CMake by Henry Schreiner
- …
```
> feat: Set range of valid CMake versions

- .github/workflows/ci.yml
CPython 3.10 is out now (:tada:) and this PR adds it to the testing matrix in the CI. The addition of the quotes on the numbers are required as YAML will view `3.10` as `3.1` if not quoted properly. :disappointed: 
---
This PR can be reviewed now but it shouldn't be merged at the moment (2021-10-07) as NumPy does not have Python 3.10 wheels out for [`numpy==1.19.3`](https://pypi.org/project/numpy/1.19.3/#files) and as a result that means that [`h5py` doesn't have Python 3.10 wheels out either](https://pypi.org/project/h5py/3.4.0/#files) given that [`h5py` requires that version during their wheel build](https://github.com/h5py/h5py/blob/4d1dcffd2ec522e45f02dcc12d02f70f3ca47d3d/tox.ini#L24) (following taken from the CI)
```
/opt/hostedtoolcache/Python/3.10.0/x64/bin/python …
```
> ci: Add Python 3.10 to testing in CI

- converters/kerasfunc2json.py
Making `converters/kerasfunc2json.py` compatible with dropout layers in  `timedistributed` type of layers.
> Improving kerasfunc2json.py compatibility

- .pre-commit-config.yaml
- src/lightweight_nn_streamers.cxx
Add and apply a pre-commit hook that enforces spaces over tabs. Additionally also enable the CRLF rejection.
Tabs are replaced with 4 spaces by default
```diff
$ git diff origin/master -- src/
diff --git a/src/lightweight_nn_streamers.cxx b/src/lightweight_nn_streamers.cxx
index 7933b7e..02f3bc0 100644
--- a/src/lightweight_nn_streamers.cxx
+++ b/src/lightweight_nn_streamers.cxx
@@ -7,7 +7,7 @@
namespace lwt {
std::ostream& operator<<(std::ostream& out,
-                          const std::vector<double>& vec) {
+               const std::vector<double>& vec) {
std::size_t nentry = vec.size();
for (std::size_t iii = 0; iii < nentry; iii++) {
out << vec.at(iii);
```
```
* Add and apply Lucas-C/pre-commit-hooks to pre-commit hooks
- Forbids …
```
> ci: Add pre-commit hook to reject tabs and CRLF from files

- include/lwtnn/generic/LightweightGraph.tcc
This should fix #161: apparently version 2.10 added some ambiguous class names.
Thanks to @iarspider for pointing out the compilation error.
> Fix for ambiguous VectorX and MatirxX types

- .github/workflows/ci.yml
- .github/workflows/lint.yml
* actions/checkout v3
- c.f. https://github.com/actions/checkout/releases/tag/v3.0.1
* actions/setup-python v3
- c.f. https://github.com/actions/setup-python/releases/tag/v3.0.0
> ci: Update GitHub Action versions to latest stable

- tests/install/CMakeLists.txt
~~This PR updates the test version installed to `v2.13` to ensure the latest version is being tested.~~
This PR removes the specification of the test version, which should safely pick up the latest version for testing.
> test:  Remove lwtnn version in tests find_package to ensure latest

- scripts/lwtnn-test-keras-functional.py
In my current version of tensorflow and keras (both 2.11.0) `get_custom_objects` has moved. As a fallback, I take the function directly from tensorflow instead when the original import fails.
In most of the code in this repository I've avoided importing `keras` or `tensorflow`, since the internals are pretty unstable. We usually just pull apart the saved model files directly. This and a few other scripts are exceptions, though. At some point I should go through and make sure they all work using `tensorflow.keras`, since the stand-alone `keras` project isn't as widely used these days.
> Fix for tensorflow api changes

- CMakeLists.txt
This is a fix in response to a problem that @krasznaa reported in [an internal ATLAS JIRA ticket](https://its.cern.ch/jira/browse/ATEAM-905).
Apparently overwriting the `CMAKE_CXX_FLAGS` here was causing all kinds of problems.
> Don't overwrite CMAKE_CXX_FLAGS, add to them
